### ISSUE TITLE
Error trying to extract certain packages for Pyre

### ISSUE THREAD

**Issue by eh-jogos** [quaerus/deppth#1]
After following the ReadMe to install I used to get the error:
```
File "/home/vandalk/.local/lib/python3.9/site-packages/deppth/compression.py", line 197, in decompress
    return lzf.decompress(chunk, chunk_size).ljust(chunk_size, b'\x00')
AttributeError: module 'lzf' has no attribute 'decompress'
```
In the README you warn that "You may need to install C++ build tools to get this dependency to install correctly." on the lzf module section of the "Dependencies". So I assume the command is failing because lzf didn't install correctly? I don't know what are these c++ build tools, or how to install then, but I eventually got past this error by using `pip install python-lzf`

Most packages extract ok, but the one I'm most interest in fails quite soon:
```
Traceback (most recent call last):
  File "/home/vandalk/.local/bin/deppth", line 8, in <module>
    sys.exit(main())
  File "/home/vandalk/.local/lib/python3.9/site-packages/deppth/cli.py", line 39, in main
    args.func(args)
  File "/home/vandalk/.local/lib/python3.9/site-packages/deppth/cli.py", line 53, in cli_extract
    extract(source, target, *entries, subtextures=subtextures)
  File "/home/vandalk/.local/lib/python3.9/site-packages/deppth/deppth.py", line 43, in extract
    entry.extract(target_dir, subtextures=subtextures)
  File "/home/vandalk/.local/lib/python3.9/site-packages/deppth/entries.py", line 231, in extract
    self._export(self._extraction_path(target) + '.png')
  File "/home/vandalk/.local/lib/python3.9/site-packages/deppth/utils.py", line 11, in wrapper
    result = fn(*args, **kwargs)
  File "/home/vandalk/.local/lib/python3.9/site-packages/deppth/entries.py", line 239, in _export
    self._get_image().save(path)
  File "/home/vandalk/.local/lib/python3.9/site-packages/deppth/utils.py", line 11, in wrapper
    result = fn(*args, **kwargs)
  File "/home/vandalk/.local/lib/python3.9/site-packages/deppth/entries.py", line 284, in _get_image
    raise Exception(f'Unsupported image format {imgformat}')
Exception: Unsupported image format 27
```
There is also a `Exception: Unsupported image format 12` when trying to extract _PlayerUnit.pkg.

I only wanted some better character protraits, so I guess what I want is really in GUI, but I also found another error with Dev.pkg
```
Traceback (most recent call last):
  File "/home/vandalk/.local/bin/deppth", line 8, in <module>
    sys.exit(main())
  File "/home/vandalk/.local/lib/python3.9/site-packages/deppth/cli.py", line 39, in main
    args.func(args)
  File "/home/vandalk/.local/lib/python3.9/site-packages/deppth/cli.py", line 53, in cli_extract
    extract(source, target, *entries, subtextures=subtextures)
  File "/home/vandalk/.local/lib/python3.9/site-packages/deppth/deppth.py", line 43, in extract
    entry.extract(target_dir, subtextures=subtextures)
  File "/home/vandalk/.local/lib/python3.9/site-packages/deppth/entries.py", line 191, in extract
    self._export(self._extraction_path(target) + '.xnb')
  File "/home/vandalk/.local/lib/python3.9/site-packages/deppth/entries.py", line 197, in _export
    with open(path, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'Dev/textures/3d/Desaturated.xnb'
```

**Comment by eh-jogos** [comment]
Oh nevermind, I was able to do it by installing "pip install python-lzf" instead of "pip install lzf"
