### ISSUE TITLE
Can't run on macOS 12.1

### ISSUE THREAD

**Issue by finscn** [quaerus/deppth#3]
the message :
```
Traceback (most recent call last):
  File "/Users/rocky/Library/Python/2.7/bin/deppth", line 5, in <module>
    from deppth.cli import main
  File "/Users/rocky/Library/Python/2.7/lib/python/site-packages/deppth/cli.py", line 45
    list_contents(path, *patterns, logger=lambda s: print(s))
```
Could help me ?  Thanks

**Comment by finscn** [comment]
My fault . I've forgotten  to use py3 ...
