### ISSUE TITLE
Can't extract lz4 file

### ISSUE THREAD

**Issue by Seirei3D** [quaerus/deppth#4]
I'm currently looking into modding Hades 2 and so far this is the only tool that I could find, that should be able to help with the lz4 files in the game.

After my attempt I got the following Error Log:
```C:\Users\Seirei\Downloads\Hades2_Test>deppth ex Melinoe_NoWeapon_Base_Idle_00.gr2.lz4
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Seirei\AppData\Local\Programs\Python\Python312\Scripts\deppth.exe\__main__.py", line 7, in <module>
  File "C:\Users\Seirei\AppData\Local\Programs\Python\Python312\Lib\site-packages\deppth\cli.py", line 39, in main
    args.func(args)
  File "C:\Users\Seirei\AppData\Local\Programs\Python\Python312\Lib\site-packages\deppth\cli.py", line 53, in cli_extract
    extract(source, target, *entries, subtextures=subtextures, logger=lambda s: print(s))
  File "C:\Users\Seirei\AppData\Local\Programs\Python\Python312\Lib\site-packages\deppth\deppth.py", line 35, in extract
    with PackageWithManifestReader(package) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Seirei\AppData\Local\Programs\Python\Python312\Lib\site-packages\deppth\sggpio.py", line 541, in __init__
    super().__init__(f'{name}', closefd, opener)
  File "C:\Users\Seirei\AppData\Local\Programs\Python\Python312\Lib\site-packages\deppth\sggpio.py", line 241, in __init__
    self._read_header()
  File "C:\Users\Seirei\AppData\Local\Programs\Python\Python312\Lib\site-packages\deppth\sggpio.py", line 356, in _read_header
    self._get_chunkprocessor()
  File "C:\Users\Seirei\AppData\Local\Programs\Python\Python312\Lib\site-packages\deppth\sggpio.py", line 80, in _get_chunkprocessor
    self.chunkprocessor = get_chunkprocessor(self.compressor)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Seirei\AppData\Local\Programs\Python\Python312\Lib\site-packages\deppth\compression.py", line 38, in get_chunkprocessor
    return _chunk_processors[b]()
           ~~~~~~~~~~~~~~~~~^^^
KeyError: b'\xf9'```

I've also tried running the file through lz4 directly and it seems like there's some metadata missing, but I'm not exactly sure about that one.

**Comment by mal4m** [comment]
I'm getting the same exact error. Have you resolved this?

**Comment by squidm0** [comment]
I ran into this error and was able to progress past it by running `pip install lz4`. After that, I encountered _another_ error, this time for missing `PIL.Image` modules, which was resolved by running `pip install pillow`. Then I thought maybe some of this was covered in the README and I just breezed past it.. and I was right. 😅 These dependencies don't _always_ need to be installed, but it seems in each of our cases they are required.

Relevant portion of the README can be found [here](https://github.com/quaerus/deppth?tab=readme-ov-file#dependencies).

In case you also end up needing to install `lzf` like I did, make sure you install C++ build tools. I followed the instructions in [this StackOverflow post](https://stackoverflow.com/a/54136652) to install.
